#ifndef _MRAM_MEMORY_H
#define _MRAM_MEMORY_H
#include <mram.h>

#ifndef NR_SLAVE_TASKLETS
#define NR_SLAVE_TASKLETS (NR_TASKLETS - 1)
#endif

#define PUSH_PACKAGE_OFFSET 0x0
#define COO_RESULT_OFFSET 0x200000
#define COO_RESULT_SIZE 0x200000
#define PULL_PACKAGE_METADATA_OFFSET (COO_RESULT_OFFSET + COO_RESULT_SIZE)
#define PULL_PACKAGE_METADATA_SIZE 0x000020

#define PRIMARY_INDEX_SPACE_ADDR ((__mram_ptr void *)(0x2000000))
#define PRIMARY_INDEX_SPACE_SIZE (0x1000000)
#define PRIMARY_INDEX_MAX_NUM 32


#define INDEX_ENTRY_BLOCKS_SPACE_ADDR ((__mram_ptr void *)(0x3000000))
#define INDEX_ENTRY_BLOCKS_SIZE (0x800000)

#endif